Script started on 2025-03-02 13:26:35-08:00
]0;jonatl41@crystalcove:hw4[jonatl41@crystalcove hw4]$ make
gcc -Wall -std=c11   -c PhotoLab.c -o PhotoLab.o
gcc -Wall -std=c11   -c FileIO.c -o FileIO.o
gcc -Wall -std=c11   -c DIPs.c -o DIPs.o
gcc -Wall -std=c11   -c Advanced.c -o Advanced.o
gcc -Wall -std=c11   -c Image.c -o Image.o
gcc -Wall -std=c11   -c Test.c -o Test.o
gcc -Wall -std=c11   -lm PhotoLab.o FileIO.o DIPs.o Advanced.o Image.o Test.o -o PhotoLab
gcc -Wall -std=c11   -DDEBUG -c PhotoLab.c -o PhotoLabTest.o
gcc -Wall -std=c11   -lm PhotoLabTest.o FileIO.o DIPs.o Advanced.o Test.o Image.o -o PhotoLabTest
]0;jonatl41@crystalcove:hw4[jonatl41@crystalcove hw4]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image horizontally
10: Add border to an image
11: Pixelate an image
12: Shift an image
13: Crop an image
14: Resize an image
15: Add Watermark to an image
16: Rotate an image by 90 degree
17: Test all functions
18: Exit
Please make your choice: 17
0 mismatching pixels (0.000%) identified in bw_diff.ppm.
0 mismatching pixels (0.000%) identified in negative_diff.ppm.
0 mismatching pixels (0.000%) identified in colorfilter_diff.ppm.
0 mismatching pixels (0.000%) identified in edge_diff.ppm.
0 mismatching pixels (0.000%) identified in shuffle_diff.ppm.
0 mismatching pixels (0.000%) identified in vflip_diff.ppm.
0 mismatching pixels (0.000%) identified in hmirror_diff.ppm.
0 mismatching pixels (0.000%) identified in border_diff.ppm.
0 mismatching pixels (0.000%) identified in pixelate_diff.ppm.
0 mismatching pixels (0.000%) identified in shift_diff.ppm.
0 mismatching pixels (0.000%) identified in crop_diff.ppm.
0 mismatching pixels (0.000%) identified in smallresize_diff.ppm.
0 mismatching pixels (0.000%) identified in bigresize_diff.ppm.
0 mismatching pixels (0.000%) identified in watermark_diff.ppm.
0 mismatching pixels (0.000%) identified in rotateby90_diff.ppm.
AutoTest finished successfully.

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image horizontally
10: Add border to an image
11: Pixelate an image
12: Shift an image
13: Crop an image
14: Resize an image
15: Add Watermark to an image
16: Rotate an image by 90 degree
17: Test all functions
18: Exit
Please make your choice: 18
You exit the program.
]0;jonatl41@crystalcove:hw4[jonatl41@crystalcove hw4]$ valgrind --leak-check=full PhotoLabTest
valgrind: PhotoLabTest: command not found
]0;jonatl41@crystalcove:hw4[jonatl41@crystalcove hw4]$ valgrind --leak-check=full PhotoLabTest[1@.[1@/
==3965056== Memcheck, a memory error detector
==3965056== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==3965056== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==3965056== Command: ./PhotoLabTest
==3965056== 
0 mismatching pixels (0.000%) identified in bw_diff.ppm.
0 mismatching pixels (0.000%) identified in negative_diff.ppm.
0 mismatching pixels (0.000%) identified in colorfilter_diff.ppm.
0 mismatching pixels (0.000%) identified in edge_diff.ppm.
0 mismatching pixels (0.000%) identified in shuffle_diff.ppm.
0 mismatching pixels (0.000%) identified in vflip_diff.ppm.
0 mismatching pixels (0.000%) identified in hmirror_diff.ppm.
0 mismatching pixels (0.000%) identified in border_diff.ppm.
0 mismatching pixels (0.000%) identified in pixelate_diff.ppm.
0 mismatching pixels (0.000%) identified in shift_diff.ppm.
0 mismatching pixels (0.000%) identified in crop_diff.ppm.
0 mismatching pixels (0.000%) identified in smallresize_diff.ppm.
0 mismatching pixels (0.000%) identified in bigresize_diff.ppm.
0 mismatching pixels (0.000%) identified in watermark_diff.ppm.
0 mismatching pixels (0.000%) identified in rotateby90_diff.ppm.
==3965056== 
==3965056== HEAP SUMMARY:
==3965056==     in use at exit: 0 bytes in 0 blocks
==3965056==   total heap usage: 162 allocs, 162 frees, 10,836,816 bytes allocated
==3965056== 
==3965056== All heap blocks were freed -- no leaks are possible
==3965056== 
==3965056== For lists of detected and suppressed errors, rerun with: -s
==3965056== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;jonatl41@crystalcove:hw4[jonatl41@crystalcove hw4]$ make clean
rm -f *.o 
rm -f PhotoLab PhotoLabTest
]0;jonatl41@crystalcove:hw4[jonatl41@crystalcove hw4]$ exitr[K
exit

Script done on 2025-03-02 13:30:10-08:00
